# Generated by Django 5.1.5 on 2025-02-04 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListaNegra",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(blank=True, default="-", max_length=255)),
                ("apellido", models.CharField(blank=True, default="-", max_length=255)),
                ("area", models.CharField(blank=True, default="-", max_length=255)),
                ("dominio", models.CharField(blank=True, default="-", max_length=255)),
                ("cargo", models.CharField(blank=True, default="-", max_length=255)),
                ("email", models.CharField(blank=True, default="-", max_length=255)),
                (
                    "localidad",
                    models.CharField(blank=True, default="-", max_length=255),
                ),
                (
                    "provincia",
                    models.CharField(blank=True, default="-", max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=255)),
                ("area", models.CharField(blank=True, max_length=255, null=True)),
                ("dominio", models.CharField(blank=True, max_length=255, null=True)),
                ("cargo", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("localidad", models.CharField(max_length=255)),
                ("provincia", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Premio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("stock", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="RegistroActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evento", models.CharField(max_length=255)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sorteo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoSorteo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sorteo_app.participante",
                    ),
                ),
                (
                    "premio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sorteo_app.premio",
                    ),
                ),
                (
                    "sorteo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sorteo_app.sorteo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SorteoPremio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden_item", models.PositiveIntegerField()),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "premio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sorteo_app.premio",
                    ),
                ),
                (
                    "sorteo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sorteopremios",
                        to="sorteo_app.sorteo",
                    ),
                ),
            ],
            options={
                "ordering": ["orden_item"],
                "unique_together": {("sorteo", "premio")},
            },
        ),
        migrations.AddField(
            model_name="sorteo",
            name="premios",
            field=models.ManyToManyField(
                through="sorteo_app.SorteoPremio", to="sorteo_app.premio"
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("localidad", models.CharField(max_length=255)),
                ("provincia", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
