# Generated by Django 5.1.5 on 2025-02-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorteo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sorteo",
            name="fecha_programada",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
